# ATTITUDE (#30)
# https://mavlink.io/en/messages/common.html#ATTITUDE

# time_boot_ms	uint32_t	ms	Timestamp (time since system boot).
# roll	float	rad	Roll angle (-pi..+pi)
# pitch	float	rad	Pitch angle (-pi..+pi)
# yaw	float	rad	Yaw angle (-pi..+pi)
# rollspeed	float	rad/s	Roll angular speed
# pitchspeed	float	rad/s	Pitch angular speed
# yawspeed	float	rad/s	Yaw angular speed
float64 roll
float64 pitch
float64 yaw
float64 rollspeed
float64 pitchspeed
float64 yawspeed