<?xml version="1.0"?>
<robot name="skbot"
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="chassisHeight" value="0.1"/>
    <xacro:property name="chassisLength" value="0.4"/>
    <xacro:property name="chassisWidth" value="0.2"/>
    <xacro:property name="chassisMass" value="50"/>

    <xacro:property name="wheelWidth" value="0.05"/>
    <xacro:property name="wheelRadius" value="0.1"/>
    <xacro:property name="wheelPos" value="0.25"/>
    <xacro:property name="wheelMass" value="5"/>

    <xacro:property name="casterRadius" value="0.05"/>
    <xacro:property name="casterMass" value="5"/>

    <xacro:property name="cameraSize" value="0.05"/>
    <xacro:property name="cameraMass" value="0.1"/>

    <xacro:include filename="$(find skbot_description)/urdf/skbot.gazebo" />
    <xacro:include filename="$(find skbot_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find skbot_description)/urdf/macros.xacro" />

    <!-- <link name="base_link">
    </link>
    <joint name="base_link_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base_link"/>
        <child link="chassis"/>
      </joint> -->
    <link name="chassis">
        <pose> 0 0 0.1 0 0 0 </pose>
        <collision>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
            <mass value="${chassisMass}"/>
            <xacro:box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
        </inertial>
    </link>
    <joint name="fixed" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
    </joint>


    <link name="caster_wheel">
        <collision>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${casterRadius}"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${casterRadius}"/>
            </geometry>
            <material name="red"/>
        </visual>

        <inertial>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
            <mass value="${casterMass}"/>
            <xacro:sphere_inertia m="${casterMass}" r="${casterRadius}"/>
        </inertial>
    </link>

    <!-- Adding Left and Right Wheels -->
    <xacro:wheel lr="left" tY="1"/>
    <xacro:wheel lr="right" tY="-1"/>

    <!-- Position Config -->
    <!-- <ros2_control name="GazeboSystem" type="system">
        <hardware>
          <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>    
        <joint name="right_wheel_hinge">
          <command_interface name="effort"/>
          <state_interface name="velocity"/>
          <state_interface name="effort"/>
        </joint>
        <joint name="left_wheel_hinge">
          <command_interface name="effort"/>
          <state_interface name="velocity"/>
          <state_interface name="effort"/>
        </joint>
      </ros2_control> -->
</robot>