controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controllers:
  ros__parameters:
    joints:
      - right_wheel_hinge
      - left_wheel_hinge
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity