site_name: WASP

theme:
  # https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
  name: material

plugins:
  - search # must be included at the first place
  # - awesome-pages:

#
# Extensions
#
markdown_extensions:
  #
  # Python Markdown
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  #
  - abbr # add a small tooltip to elements
  - admonition # add call-out blocks
  - attr_list # allow to add HTML attributes and CSS classes
  - def_list # add description lists
  - footnotes # define inline footnotes
  - meta # attach arbitrary key-value pairs to a document
  - md_in_html # allow to write Markdown inside HTML elements
  - tables # create tables in Markdown
  - toc: # generate a table of contents from documents
      permalink: '#' # anchor
      toc_depth: 4 # header 1 to header 4
      slugify: !!python/name:pymdownx.slugs.uslugify # convert title to html-compatible text
  - sane_lists # make better lists
  - smarty: # convert some special characters
      smart_angled_quotes: true

  #
  # Python Markdown Extensions
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  #
  - pymdownx.arithmatex: # render math equations
      generic: true
  # - pymdownx.betterem: # improve the detection of Markup to emphasize text in Markdown
      # smart_enable: all
  - pymdownx.caret # define superscript
  - pymdownx.mark # highlight text
  - pymdownx.tilde # define subscript
  - pymdownx.critic # track changes
  - pymdownx.details # add collapsible call-outs
  - pymdownx.emoji: # add inlines bundled and custom icons and emojis 
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # define code blocks and nesting of code
  - pymdownx.highlight: # highlight of code blocks
      linenums_style: pymdownx-inline
      # anchor_linenums: true # create anchor link on each line of code
  - pymdownx.inlinehilite # highlight inline code blocks
  - pymdownx.smartsymbols # convert some sequences of characters into their corresponding symbols
  - pymdownx.snippets #  embed content from arbitrary files into a document
  - pymdownx.tabbed: # group related content and code blocks under accessible tabs
      alternate_style: true
  - pymdownx.tasklist: # define list of task with checkbox
      custom_checkbox: true
  - pymdownx.escapeall:
      hardbreak: true # use \ to create new line
      nbsp: true # use \<space> to create &nbsp;
  # - pymdow